### ISSUE TITLE
 PHP Fatal Error - Content-type Page

### ISSUE THREAD

**Issue by WegPast** [jf-guillou/lcds#2]
When i try to reach this page : `lcds-server/content-type` I get this error : 
`PHP Fatal Error – yii\base\ErrorException`
`Cannot instantiate abstract class app\models\types\Media`

Error stack :

```php
1. in /var/www/lcds/models/ContentType.php at line 118

     *
     * @param array $row
     *
     * @return array transformed row
     */
    public static function instantiate($row)
    {
        $typeClass = self::fromType($row['id']);
 
        return new $typeClass(); //line:118
    }
 
    /**
     * Get raw data and transform it to content type specific needs.
     *
     * @param string $data
     *
     * @return string transformed data
     */
2. yii\base\ErrorHandler::handleFatalError()
```

I didn't do anything yet, just wanted to wander around the application a bit, understanding how it works ^^
Maybe i have to configue somthing first ?

_ps: I said it, that I would bring forward other bugs :p_
_ps2: Cool, l'interface est déjà en français \o/_

**Comment by jf-guillou** [comment]
Hey, thanks again !

Every bug you're encountering results in poor testing from my part.

Hopefully, the latests commits should have fixed them.
Don't forget to [update](https://github.com/jf-guillou/lcds#upgrade)!
